### ISSUE TITLE
extra runtime dependency on setuptools

### ISSUE THREAD

**Issue by stanislavlevin** [serge-sans-paille/beniget#105]
With 732bf64a2fb8d8ae9b6e6413198cb6ce99106f63 `setuptools` is strict runtime dependency, but I can't
see where it's used. So far it's only needed for build.

**Comment by serge-sans-paille** [comment]
Also pusged a release update tagged as 0.4.2.post1

**Comment by stanislavlevin** [comment]
Thank you!
