### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by martinRenou** [serge-sans-paille/beniget#11]
beniget prints some warning for unbound identifiers, could it be possible to have a silent mode that does not print those warnings?

I can come up with a PR.

**Comment by serge-sans-paille** [comment]
PR are welcome, yes!

**Comment by serge-sans-paille** [comment]
Note that if you want a silent mode, you can just follow the path i adopted in
Pythran:

https://github.com/serge-sans-paille/pythran/blob/master/pythran/analyses/use_def_chain.py#L16

**Comment by serge-sans-paille** [comment]
@martinRenou closing this issue as subclassing is the way to go
