### ISSUE TITLE
Read Code from Python File

### ISSUE THREAD

**Issue by foadjn** [serge-sans-paille/beniget#27]
Hi,

I am working on a research project, and I am using beniget for part of my research problem. An issue I found was about reading code from a python file. When I am working with several files or apply changes to one file, I should prepare my code such that beniget can process it. I wondered if it is possible to add a feature so beniget can read code from a file.

**Comment by serge-sans-paille** [comment]
I'm not quite sure I understand your issue. A typical usage of beniget, reading from a string, would be

```
>>> code = "from math import cos, sin; print(cos(3))"
>>> module = ast.parse(code)
>>> duc = beniget.DefUseChains()
>>> duc.visit(module)
```

Reading from a file, that would be

```
>>> with open(filename, 'r') as fd:
...    code = fd.read()
...    module = ast.parse(code)
...    duc = beniget.DefUseChains()
...    duc.visit(module)
```

But what's « another file » ?

**Comment by foadjn** [comment]
Regarding another file, I meant a file. You addressed it in your example.
