### ISSUE TITLE
Make it work with the standard library

### ISSUE THREAD

**Issue by tristanlatr** [serge-sans-paille/beniget#45]
I believe very little effort is needed to make it work on python3 with the `ast` module. 
Of course, this would only work on python3 for python3 ast. But compatibility with python2 would still be possible by installing `gast`.

What do you think ?

**Comment by serge-sans-paille** [comment]
I understand your need, but I don't see myself maintaining this extra approach. I *think* it could be possible to achieve a similar approach by subclassing `gast.Ast3ToGAst` and defining your own `ast_to_gast`, and this could be done on the client side.
