### ISSUE TITLE
Something is not right with comprehensions

### ISSUE THREAD

**Issue by tristanlatr** [serge-sans-paille/beniget#57]
Hello Serge,

I've noticed a stange bug while running beniget on pydoctor's code, here the command I used to reproduce the bug:

```
python3 -m beniget.beniget ../pydoctor/pydoctor/astbuilder.py 
<frozen runpy>:128: RuntimeWarning: 'beniget.beniget' found in sys.modules after import of package 'beniget', but prior to execution of 'beniget.beniget'; this may result in unpredictable behaviour
W: unbound identifier 'name' at ../pydoctor/pydoctor/astbuilder.py:388:23
W: unbound identifier 'name' at ../pydoctor/pydoctor/astbuilder.py:385:16
[...]
```

which points to code like:
```python
            names = [
                name
                for name in chain(mod.contents.keys(),
                                  mod._localNameToFullName_map.keys())
                if not name.startswith('_')
                ]
```

I cannot reproduce it inside the tests, thought :/

I've made sure that no older version of beniget is installed on my site-packages. I don't really understand the python warning... But it seems it could be linked to the [project structure](https://stackoverflow.com/questions/43393764/python-3-6-project-structure-leads-to-runtimewarning), so it's likely unrelated. 

Tell me what you think,

**Comment by serge-sans-paille** [comment]
I can reproduce your issue, digging...

**Comment by serge-sans-paille** [comment]
reproducer:
```
def reproducer(self):
    names = [name for name in self if name]

    for name in names:
        self[name] = 1
```
