### ISSUE TITLE
Discussing semantics of Def.name()

### ISSUE THREAD

**Issue by tristanlatr** [serge-sans-paille/beniget#98]
``Def`` is confusing on several points:
- There is no way of knowing if a `Def` actually has a name or the string returned by `name()` is a node type name, which can be confusing when there are definitions named like ast classes. I think if the name is the class name it should be returned as such : `f'<{type(self.node).__name__.lower()}>'` 
- `ast.Attribute` instances have no name, I think that their name should be the `node.attr` value.

**Comment by serge-sans-paille** [comment]
I agree! I've submitted ~99 for the attribute part, would you handle the type name part? I agree with your naming scheme for types.
